### ISSUE TITLE
¿Existe un SRID estándar?

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#1]
¿El "Sistema de Proyección Único para Colombia" también es un estándar internacional?

Por ejemplo, [EPSG:3115 seems not](https://spatialreference.org/ref/epsg/3115/ ) parece que no, pero confirmes aquí Luis que no existe.

Si no existe: defina un SRID pseudoestándar en esta biblioteca pública,<br/>https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-extraSRID.sql

----

(original English deprecated)

The "Sistema de Proyección Único para Colombia" is also an international  standard?

For example [EPSG:3115 seems not](https://spatialreference.org/ref/epsg/3115/ ), but please **confirm** here that it not exists.

If not exists: please define a pseudo-standard SRID at this public library,<br/>  https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05pgis-extraSRID.sql

**Comment by luisfelipebr** [comment]
Según [IGAC](https://origen.igac.gov.co/herramientas.html), es **EPSG: 9377**, pero no pude encontrarlo en [Spatial Reference](https://spatialreference.org/ref/epsg/9377/).

PROJCS para implementación:
```
PROJCS["MAGNA-SIRGAS / Origen-Nacional",
    GEOGCS["MAGNA-SIRGAS",
    DATUM["Marco_Geocentrico_Nacional_de_Referencia",
    SPHEROID["GRS 1980",6378137,298.257222101,
    AUTHORITY["EPSG","7019"]],
    TOWGS84[0,0,0,0,0,0,0],
    AUTHORITY["EPSG","6686"]],
    PRIMEM["Greenwich",0,
    AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
    AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4686"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",4.0],
    PARAMETER["central_meridian",-73.0],
    PARAMETER["scale_factor",0.9992],
    PARAMETER["false_easting",5000000],
    PARAMETER["false_northing",2000000],
    UNIT["metre",1,
    AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","9377"]]
```

Proj4:
```
+proj=tmerc +lat_0=4.0 +lon_0=-73.0 +k=0.9992 +x_0=5000000 +y_0=2000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```
