### ISSUE TITLE
Códigos absutos da base16h na interface teste

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#12]
Os códigos postais e mais populares são base32, já temos por exemplo `CO~12345` como geocódigo absoluto da Colômbia. Para se ter acesso a todos os níveis da grade, necessário em aplicações estatísticas e científicas, é oferecida também a [base 16h](http://osm.codes/_foundations/art1.pdf). 

Sintaxe: `CO+12345`  

![image](https://user-images.githubusercontent.com/1651447/176169082-1dfc3046-74d2-4a96-90d3-f22c17acca86.png)

O nível zero da base 16h fará uso de 2 dígitos, representando as coordenadas ij da matriz de células e conforme ordem dos eixos no  sistema de coordenadas da projeção.

---

Notas

* ver [diretivas deste comentário](https://github.com/osm-codes/WS/issues/9#issuecomment-1168587740).
* [Planilha da métrica dos níveis](https://docs.google.com/spreadsheets/d/1fIfJ96scSg9Srh0F8-RiMfdqLCdctUI3_qUN0829SFY/edit#gid=640676951)
* [Simulações da base 16h](https://ppkrauss.github.io/Sfc4q/)

**Comment by 0e1** [comment]
Me parece que já foi implementado e está em funcionamento.
