### ISSUE TITLE
Na interface mostrar cobertura municipal indexada por default

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#14]
[A orientação ao contexto já é uma diretiva](https://github.com/osm-codes/WS/issues/22)... Então enfatizar o código indexado será o mais natural a fazer na interface.

Por exemplo em  http://osm.codes/CO-ANT-Medellin no modo "with cover" ao invés de mostrar rótulos de grade absoluta, 
mostrar já os rótulos de 1 dígito da indexação. Queremos enfatizar o município, o usuário não quer saber de nada fora do município quando o escopo é o **geocódigo postal** (base32).

* no lugar de `8VR` usar **`2`** ou `~2`
* no lugar de `9K2` usar **`8`** ou `~8`
* no lugar de `9K0` usar **`6`** ... etc

Alias todos os rótulos de geocódigo postal podem ser `~XX`  e só quando clica aparece `CO-ANT-Medellin~XX`.
 
![image](https://user-images.githubusercontent.com/1651447/180886059-e545b765-d96b-4718-9335-5de662937267.png)

**Comment by 0e1** [comment]
Implementado.

![Captura de tela de 2022-07-26 13-52-04](https://user-images.githubusercontent.com/41844788/181065574-983fce8c-5b98-44d4-9e75-5e2efdb68c66.png)
![Captura de tela de 2022-07-26 13-54-37](https://user-images.githubusercontent.com/41844788/181065581-b0ac7ea2-0e18-4266-b74e-6fc7f9b29fde.png)

**Comment by ppKrauss** [comment]
Desculpe, [aqui padronizamos de outra forma o  relativo](https://inde.gov.br/images/inde/poster3/Expans%C3%A3o%20do%20protocolo%20GeoURI.pdf),  usar o ponto no inicio ao invés do `~`... É como path relativo do Unix.

**Comment by 0e1** [comment]
Ajustado!
