### ISSUE TITLE
Interface de cobertura municipal parou de funcionar

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#15]
![image](https://user-images.githubusercontent.com/1651447/182023758-b2fdcf2c-c52b-43bd-9aa5-18c3ee121c65.png)

Não funciona com Óbitos nem BR-SP-SaoCaetanoSul mas funciona com Campinas e Medellin... Mas Óbitos e SaoCaetanoSul estão gerando geocódigo curto

**Comment by 0e1** [comment]
Bem, com _Óbitos_ não vai funcionar, porque a grafia é _Óbidos_.

Quanto a São Caetano do Sul, tinhamos um problema na cobertura. Uma célula da cobertura possuia interserção vazia com a geometria da jurisdição. https://osm.codes/geo:iso_ext:BR-SP-SaoCaetanoSul.json/cover retornava o geojson com essa célula, mas a interface não conseguia consumir o geojson com uma feature sem coordenadas.
![Captura de tela de 2022-08-01 16-07-08](https://user-images.githubusercontent.com/41844788/182235807-e5e39cc4-5899-4605-8351-0bc55d750192.png)

Corrigi a cobertura é agora está funcionando.
