### ISSUE TITLE
Não mostrar código base32 absoluto

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#16]
<img align="right" width="320" src="https://user-images.githubusercontent.com/1651447/186845958-83235c82-b2ce-4595-8c34-0174dfc11335.png">

O código base32 absoluto causa grande confusão pela mudança de dígito na indexação. Na popup do exemplo,  [CO-RIS-Dosquebradas~15NTJ](http://osm.codes/CO-RIS-Dosquebradas~15NTJ), melhor expressar:
* Municipio: `RIS-Dosquebradas`
* postal code: `15NTJ`
* grid code: (base16h code)
* area, side, etc. ok

A visão do código absoluto só é util como "evidência de teste" para comprovar que mudanças territoriais não afetariam a geocodificação, exceto seus prefixos nas zonas impactadas por mudança. Precisa aparecer na interface apenas quando solicitada.

Nas explicações precisaria de destaque, `15NTJ` na verdade tem `1` como "cover-index code" e `5NTJ` como "base32 location suffix".  Só este último que não corre risco de sofrer impacto nas mudanças territoriais.

**Comment by 0e1** [comment]
> Precisa aparecer na interface apenas quando solicitada.

Especificar como/onde deve ser a solicitação.



> Nas explicações precisaria de destaque, `15NTJ` na verdade tem `1` como "cover-index code" e `5NTJ` como "base32 location suffix". Só este último que não corre risco de sofrer impacto nas mudanças territoriais.

Como deve ser o popup? Seria esse um exemplo completo:

Municipio: RIS-Dosquebradas
postal code: 15NTJ
grid code: (base16h code)
cover-index code: 1
base32 location suffix: 5NTJ
area: 64 m2
side: 8 m

?
Especificar detalhes, como por exemplo: se deve usar maiúscula em _Municipio_?

**Comment by ppKrauss** [comment]
> Especificar como/onde deve ser a solicitação.

Pode ser uma checkbox de "infos grade postal". 

> Como deve ser o popup? Seria esse um exemplo completo:

```
postal code: <big><code>15NTJ</code></big>
local: <code>RIS-Dosquebradas</code>
local code: (DIVIPOLA)
grid b16h: (base16h code)
area: 64 m²
side: 8 m
```

**Comment by 0e1** [comment]
Ver https://github.com/osm-codes/CO_new/issues/17
