### ISSUE TITLE
Introduzir abreviações para os códigos postais e permitir hifem

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#17]
Está pendente trazer as abreviações da Colômbia e publicar a lista de-para dessas abreviações a cada departamento.

Uma vez legitimadas as abreviações, elas podem ser tratadas como "oficiais do código postal". Assim as referências em nome seriam sempre reduzidas na URL a referências em abreviação.
 
Quanto ao so do hifem , "-", no lugar de "\~", atualmente podemos referenciar cidades através do nome, por exemplo [CO-RIS-Dosquebradas-15NTJ](http://osm.codes/CO-RIS-Dosquebradas-15NTJ)  ou através de DIVIPOLA (jurisd_local_id), [CO-66170-15NTJ](http://osm.codes/CO-66170-15NTJ), e ambos retornam o canônico (com "\~").

**Comment by 0e1** [comment]
> Está pendente trazer as abreviações da Colômbia e publicar a lista de-para dessas abreviações a cada departamento.

Indicar a localização das abreviações.


> retornam o canônico (com "~")

quer dizer a url ser exibida com "~"?

**Comment by ppKrauss** [comment]
@0e1  fazer merge desta issue com aquela das tabelas de referência-abreviação, onde as mesmas estão sendo controladas.

Quanto à URL e representações canônicas, sim, sempre com o `~`  separando, mas os usuários preferem usar `-` de modo que não é exigido como formato de *input*, apenas formatação *output* canônica.

**Comment by 0e1** [comment]
Foram adicionadas as abreviações de Colombia em `optim.jurisdiction_abbrev_option`.
Abreviações repetidas foram marcadas com _false_.

Elas já estão em uso, por exemplo: http://osm.codes/CO-RIS-DQS-15NTJ.

Também disponível a alteração para canônica, por exemplo, de `CO-RIS-DQS-15NTJ` para `CO-RIS-Dosquebradas~15NTJ`

Ainda pendente:
* publicar as abreviações

**Comment by 0e1** [comment]
> Ainda pendente:
> 
>     * publicar as abreviações

@ppKrauss:  por gentileza especificar como deve ser a publicação das abreviações.

**Comment by ppKrauss** [comment]
Assim como o código redireciona, a abreviação deve redirecionar para o nome completo.
Exemplos:
* [x] CO-A-Itagui = redirecionar para CO-ANT-Itagui
* [x] código Divipola = redirecionar para CO-ANT-Itagui
* [x] CO-A-Igi  = abreviação redirecionar CO-ANT-Itagui
* [x] CO-ANT-Igi  = abreviação redirecionar CO-ANT-Itagui

**Comment by ppKrauss** [comment]
* [x] Bug menor: o link http://osm.codes/CO-RIS-Pereira~95NTJ   entra com Level 0, precisa entrar com L15 que é o do 8m fornecido. 

No caso de http://osm.codes/CO-RIS-Pereira  entrar com L-1 do level da menor covertura. Nesse caso de Pereira, como a cobertura menor é L5, o L-1 seria L7.5. O "-1" é aplicado à array da sequência de níveis base32.

* [x] Outro bug menor: calculo de área e size diferenciado para célula de cobertura de fronteira, visto que uma coisa é a caracterização da célula por seu Level e size típicos da grade, outra coisa é o recorte geométrico.

![image](https://user-images.githubusercontent.com/1651447/192755032-35fbab29-1558-497b-9201-cea5eed08946.png)





***
O click descritor não mostra mais o nome da cidade nem nada,
image.png


BUGs menores para decidir o que fazer:
* [x] https://osm.codes/CO-ANT-Medellin  = interface não remove cover, seu eu precisar clicar ponto fica preso.
* [x] https://osm.codes/CO-ANT-Medellin~123 = funciona mas não mostra 123 ao clicar no quadrado, precisa usar a forma indexada e com nome da cidade.
* ~~https://osm.codes/CO-Medellin~123  Não funciona, mas tudo bem...~~
* [x] https://osm.codes/CO-5001  não redireciona para https://osm.codes/CO-ANT-Medellin

**Comment by 0e1** [comment]
De https://github.com/osm-codes/CO_new/issues/16:

> O código base32 absoluto causa grande confusão pela mudança de dígito na indexação. 
> 
> A visão do código absoluto só é util como "evidência de teste" para comprovar que mudanças territoriais não afetariam a geocodificação, exceto seus prefixos nas zonas impactadas por mudança. Precisa aparecer na interface apenas quando solicitada.
>
> Pode ser uma checkbox de "infos grade postal".

* [ ] Pode ser uma checkbox de "infos grade postal"

**Comment by 0e1** [comment]
Assunto sobre publicação segue na issue https://github.com/osm-codes/WS/issues/31. 
Definições citadas nessa issue foram consolidades no rascunho https://wiki.addressforall.org/doc/osmc:Api.
