### ISSUE TITLE
Caja de cuadrícula, definir 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#2]
En la secion sobre [Proyección adoptada](https://github.com/osm-codes/CO_new#proyecci%C3%B3n-adoptada-y-origen) ilustramos la  "Caja de cuadrícula", pero no es una proposta final. Es necesario refinar: **pendente** definir los parametros de la caja:

* El origem, `(x0,y0)`  de la caja. 
* El  tamaño del lado de lo cuadrado en miles de km 

los valores son relativamente arbitrarios, se pueden redondear.

---- 
La imagen actual **es incorrecta**, es solo un boceto ilustrativo. Aquí vamos a definir mejor.

![](https://github.com/osm-codes/CO_new/raw/main/assets/ilustra-grade01.jpeg)

**Comment by luisfelipebr** [comment]
Sigue el cuadro delimitador (bbox) de los [layers](https://www.openstreetmap.org/relation/120027#map=3/-2.67/-48.94) para ayudar a definir el origen y el tamaño del lado, incluido el mar territorial.

Con islas:
xmin = 4003715
ymin = 1089833
xmax = 5685106
ymax = 3343880

Sin islas:
xmin = 4304477
ymin = 1089833
xmax = 5685106
ymax = 2957996

**Comment by ppKrauss** [comment]
> Sigue el cuadro delimitador (bbox) de ...

¡Muy bien Luiz, resuelto! ¿Sería posible agregar en /assets imágenes ilustrativas de los dos recuadros, resaltando en rojo o amarillo los respectivos puntos de origen (*x₀*, *y₀*)?

**Comment by luisfelipebr** [comment]
> ¡Muy bien Luiz, resuelto! ¿Sería posible agregar en /assets imágenes ilustrativas de los dos recuadros, resaltando en rojo o amarillo los respectivos puntos de origen (_x₀_, _y₀_)?

Claro. Puse la imagen en [assets](https://github.com/osm-codes/CO_new/blob/main/assets/bbox-v1.png), agregando un búfer de 5 km

**Comment by ppKrauss** [comment]
> Sigue el cuadro delimitador (bbox) ... 
> Con islas: xmin = 4003715 ymin = 1089833 xmax = 5685106 ymax = 3343880
> Sin islas: xmin = 4304477 ymin = 1089833 xmax = 5685106 ymax = 2957996

Puedes destacar el *xmin* y *ymin* con y sin islas?  Se perdido con el buffer

**Comment by ppKrauss** [comment]
Ok, resaltando con ![](https://github.com/osm-codes/CO_new/raw/main/assets/bbox-v3mins.800px.png)
