### ISSUE TITLE
Usar a fonte FE-Schrift na interface de mapa ou apresentação do geocódigo

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#3]
A fonte tipográfica utilizada nas placas de carro do Mercosul,  [FE-Schrift](https://pt.wikipedia.org/wiki/FE-Schrift), é comprovadamente mais legível (para humanos e computadores), evitando ambiguidade entre letras. Quando se tratar de geocódigo misto (p. ex. `CO-MAG-SantaMaria~3T6L-L1K`), usar, como na placa, o prefixo nominal (CO-MAG-SantaMaria) com tamanho de fonte menor (de 50% a 75%).

Abaixo a comparação do uso da fonte apenas no final do geocódigo, e no geocódigo inteiro, com ou sem ponto de separação &mdash; tendo em vista que a fonte não oferece representação de letras minúsculas.

![image](https://user-images.githubusercontent.com/1651447/174921448-3fbc182b-fca7-4327-9d30-c133801cce5a.png)

Em mapas ou interfaces de apresentação de pontos pode-se adotar a expressão sem o "~", em duas linhas:
![image](https://user-images.githubusercontent.com/1651447/174922329-74ad0dab-ef46-4534-8ea7-28660edbe22b.png)

Em placas de numeração predial, onde o contexto é certo e conhecido, pode-se omitir o contexto ou fazer uso do geocódigo absoluto, por exemplo `BR~123-XY234Z`.

Todos os símbolos (glifos) da fonte e seu uso típico nas placas de automóveis do Mercosul:

![image](https://user-images.githubusercontent.com/1651447/172559194-e52cb83c-8431-4338-a8d4-70d825b9d5fa.png)

![image](https://user-images.githubusercontent.com/1651447/172559036-da1a6d51-316e-4747-ba42-8f67e2ef3575.png)

**Comment by ppKrauss** [comment]
Sempre consultar [conteúdos fiáveis  em inglês](https://en.wikipedia.org/wiki/FE-Schrift). Quanto ao formatos, no site preferir *"WOFF (and its successor WOFF2) are compressed file formats created specifically for web fonts"*, aos demais como TTF ou OTF. WOFF é de 2009 ([rec atualizada em 2012](https://www.w3.org/TR/WOFF/)), porém  só 30% menos compacto que WOFF2 de 2018 ([rec atualizada em 2022](https://www.w3.org/TR/WOFF2/)), portanto WOFF ainda hoje satisfatório e mais freequentemente disponivel.

Baixar fonte original  e testar, opções:
* [TTF baixar daqui](https://www.andyhoppe.com/files/EuroPlate.ttf) (converter em WOFF2) o descrito em https://www.andyhoppe.com/design/fonts/euro-plate-font/ 
* ... outras? Ver [similares](https://www.dafont.com/pt/search.php?q=FE-Schrift)... Mesmo Car-GO2 com alguns caracteres a mais, não possui `~`  nem outras pontuações, nem minúsculas.
 
Testar conforme [dev Mozilla/font-fac](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#examples) ou [Stack](https://stackoverflow.com/a/24990642/287948)

```css
@font-face {
  font-family: 'FE-Schrift';
  src: URL('path/FE-Schrift.woff') format('woff');
}
```
PS: [neste link com form download PDF](https://www.servinglibrary.org/journal/3/falschungserschwerende-schrift)  a história do desenvolvimento da fonte lembra que foi também testado para ser leígivel (sem ambiguidades usuais de O-0, I-l, W-vv, etc.) e eficiente com OCR, o que se confirma com a leitura OCR placas do Brasil. O mesmo OCR otimizado para placas estaria otimizado para placas de numeração predial ou textos com descrição de endereço postal.

**Comment by 0e1** [comment]
https://github.com/osm-codes/gridMap-draftPages/issues/9
