### ISSUE TITLE
Mostrar Jurisdição recordata por subdivisão nominal

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#5]
Exemplo https://osm.codes/CO-ANT-Itagui-O deceria retonar a célula Oeste recortada por Itagui.

**Comment by 0e1** [comment]
Funcionalidade implementada em https://github.com/osm-codes/CO_new/commit/2cb1f7d11fadfc3e3d53b48082ac37cd5be8101b, juntamente com reorganização do código (para ser possível [inicializar a base](https://github.com/osm-codes/CO_new/wiki/Testes-de-api#cria%C3%A7%C3%A3o-da-base-de-dados)) e, também, com a remoção da dependência de uma base _ingest_, criando _fdw_ para `dl03t`. Melhorei, também o código do vizualizador em [src/site](https://github.com/osm-codes/CO_new/tree/main/src/site).

Notar que a resolução de nomes está sendo considerada. Então, são esquivalentes:

https://osm.codes/CO-ANT-Itagui-O
https://osm.codes/CO-A-Itagui-O
https://osm.codes/CO-Itagui-O
