### ISSUE TITLE
Tratamento do nome da capital, CO-DC

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/CO_new#8]
O geocódigo ISO `CO-DC`  precisa ser implementado como sinônimo de `CO-DC-Bogota` (canônico) ... Ou o inverso já que DC é mais curto e igualmente oficial.

**Comment by 0e1** [comment]
O commit https://github.com/digital-guard/preserv/commit/73ca5b396f1cada22bfc6fe60736f24dbfb32dd6 faz a associação `CO-DC -> CO-DC-Bogota`.
Ele também corrige um defeito na geração de nomes curtos, uma vez que DC é um departamento com duas letras, enquanto os demais possuem 3. Na view estava aparecendo `CO-ogota` ou `CO-D-ogota`.
